# Generated by Django 3.1.4 on 2021-01-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
