# Generated by Django 3.1.4 on 2021-01-27 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=700, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('genre', models.CharField(max_length=60, verbose_name='Жанр')),
                ('author', models.CharField(max_length=35, verbose_name='Автор')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранная')),
                ('year', models.DateTimeField(verbose_name='Год издания')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Добавление книги на сайт')),
            ],
            options={
                'verbose_name': 'Книжный магазин',
                'verbose_name_plural': 'Книжные магазины',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранная'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Задача'),
        ),
    ]
